discord:
  bot_token: "YOUR_DISCORD_BOT_TOKEN"
  guild_id: "123456789012345678"
  channel_id: "123456789012345678"

messages:
  join: "{player} joined the game."
  quit: "{player} left the game."
  chat: "{player} -> {message}"